#%RAML 1.0
title: INF4375
baseUri: http://localhost:3000
version: 1

/api:
    /contrevenants:
        get:
            description: Obtenir la liste des contrevenants entre deux dates.
            queryParameters:
                du:
                        description: Une chaîne de caractères qui doit être une
                                     date de départ respectant ISO8601.
                        type: string
                        required: true
                        example: 2016-01-01
                au:
                        description: Une chaîne de caractères qui doit être une
                                     date de fin plus tard que la date de début
                                     respectant ISO8601.
                        type: string
                        required: true
                        example: 2016-01-02
            responses:
                200:
                    description: La liste des contrevenants a bien été envoyé.
                500:
                    description: Une erreur interne s'est produite.
    /doc:
        get:
            description: Obtenir la documentation des services REST.
            responses:
                200:
                    description: La liste des contrevenants a bien été envoyé.
                500:
                    description: Une erreur interne s'est produite.
    /infractions:
        get:
            description: Obtenir une liste des établissements avec leur nombre d'infractions en JSON.
            responses:
                200:
                    description: La liste des infractions a bien été envoyée.
                500:
                    description: Une erreur interne s'est produite.
    /infractionsxml:
        get:
            description: Obtenir une liste des établissements avec leur nombre d'infractions en XML.
            responses:
                200:
                    description: La liste des infractions a bien été envoyée.
                500:
                    description: Une erreur interne s'est produite.
    /infractionscsv:
        get:
            description: Obtenir une liste des établissements avec leur nombre d'infractions en CSV.
            responses:
                200:
                    description: La liste des infractions a bien été envoyée.
                500:
                    description: Une erreur interne s'est produite.
    /modifycv:
        post:
            description: Modifier un contrevenant via un objet JSON envoyé.
            body:
                application/json:
                    schema: !include ../schemas/modifycv.json
            responses:
                200:
                    description: La liste des contrevenants a bien été modifié.
                500:
                    description: Une erreur interne s'est produite.
    /deletecv:
        delete:
            description: Supprimer un contrevenant via un Id.
            responses:
                200:
                    description: Le contrevenant a bien été supprimé.
                500:
                    description: Une erreur interne s'est produite.
    /modifywindow:
        get:
            description: Retourne un formulaire HTML pour la modification d'un contrevenant.
            queryParameters:
                id:
                    description: Le Id 24hex du contrevenant à modifier.
                    type: string
                    required: true
                    example: 5849f3d90296ed13a87632b8
            responses:
                200:
                    description: Le formulaire a bien été envoyé.
                500:
                    description: Une erreur interne s'est produite.
    /etablissement:
        get:
            description: Obtenir les contrevenants par un établissement.
            responses:
                200:
                    description: La liste des contrevenants a bien été envoyé.
                500:
                    description: Une erreur interne s'est produite.
